/** TEST-ONLY Vite config: serves the generator-produced manifest + synthetic PNGs
 * (staged into ./generated by global-setup) so the browser fetches them over real HTTP. */
import { defineConfig } from 'vite';

export default defineConfig({
  root: __dirname,
  publicDir: 'generated',
  server: { port: 5180, strictPort: true },
  preview: { port: 5180, strictPort: true },
});
